export const clientReviews = [
  {
    id: 'review-01',
    companyName: 'Gulf Horizon Group',
    testimonial: 'Speedup Services helped us standardize facility onboarding across 15 sites in six months, reducing operational incidents by 40%. Their response time was unmatched and everything was delivered on schedule.',
    clientName: 'Noura Al-Mansour',
    clientTitle: 'Head of Operations, Gulf Horizon Group',
    category: 'facility',
  },
  {
    id: 'review-02',
    companyName: 'Riyadh Business Solutions',
    testimonial: 'Our workforce needs were volatile, but Speedup Services provided rapid qualified staffing for seven major projects. Project execution became smoother and customer satisfaction jumped by 18%.',
    clientName: 'Fahd Al-Harbi',
    clientTitle: 'Director of HR, Riyadh Business Solutions',
    category: 'manpower',
  },
  {
    id: 'review-03',
    companyName: 'Saudi Prime Logistics',
    testimonial: 'With a 22% improvement in inbound logistics efficiency, Speedup Services transformed our last-mile operations. Their team is both agile and reliable.',
    clientName: 'Layla Al-Qahtani',
    clientTitle: 'Supply Chain Director, Saudi Prime Logistics',
    category: 'logistics',
  },
  {
    id: 'review-04',
    companyName: 'Al Noor Facilities',
    testimonial: 'A true partnership: proactive facility audits, preventive maintenance excellence, and fast issue resolution. Our asset uptime is now over 99.1%.',
    clientName: 'Sultan Al-Farhan',
    clientTitle: 'General Manager, Al Noor Facilities',
    category: 'facility',
  },
  {
    id: 'review-05',
    companyName: 'Vision Edge Media',
    testimonial: 'Creative campaigns and fast-turn design deliverables made us stand out during Ramadan. We saw 37% higher engagement and a 21% increase in leads.',
    clientName: 'Dima Al-Saadi',
    clientTitle: 'Marketing Head, Vision Edge Media',
    category: 'creative',
  },
  {
    id: 'review-06',
    companyName: 'Apex Financial Partners',
    testimonial: 'Financial process setup from Speedup Services reduced cycle time by 25% and significantly improved claim reconciliation across sister companies.',
    clientName: 'Mohammed Al-Bader',
    clientTitle: 'Finance Director, Apex Financial Partners',
    category: 'financial',
  },
  {
    id: 'review-07',
    companyName: 'Desert Line Contracting',
    testimonial: 'Speedup Services delivered a complete operational toolkit for our construction logistics, making compliance and standards our competitive differentiator.',
    clientName: 'Sara Al-Zahrani',
    clientTitle: 'COO, Desert Line Contracting',
    category: 'logistics',
  },
  {
    id: 'review-08',
    companyName: 'FutureScale Retail',
    testimonial: 'Marketing automation and digital transformation support from Speedup Services accelerated our campaign cadence. Quarter-over-quarter conversion rates are now 31% higher.',
    clientName: 'Mansour Al-Mutairi',
    clientTitle: 'Chief Digital Officer, FutureScale Retail',
    category: 'digital',
  },
];
